server:
  port: 9003

spring:
  ## 数据源
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.129.140.43:1521:orcl
#    username: MSSP
#    password: MSSP
    url: jdbc:oracle:thin:@10.129.140.151:1521/ORCL
    username: czcb_admin
    password: ea6h4qjv

logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath*:mapper/*.xml





